- name: "Instalacion de isc-dhcp-server"
  apt:
    pkg:
      - isc-dhcp-server
      - iptables
- name: "/etc/network/interfaces"
  template:
    src: interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'
  notify:
    - reiniciar maquina

- name: "Añadir clave pública ssh"
  authorized_key:
    user: user-server
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: "Bit de forwarding"
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    
- name: "Cambiar la plantilla de /etc/dhcp/dhcpd.conf"
  template:
    src: dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - reiniciar dhcp

- name: "Cambiar la plantilla de /etc/default/isc-dhcp-server"
  template:
    src: isc-dhcp-server
    dest: /etc/default/isc-dhcp-server
    owner: root
    group: root
    mode: '0644'
  notify:
    - reiniciar dhcp
